name: CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Deploy to EC2 using SSH Action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            set -euo pipefail
            cd Feedback-Sentiment

            git fetch -q origin main
            git reset --hard origin/main
            echo "Deploying latest commit on main: $(git rev-parse HEAD)"

            export COMPOSE_DOCKER_CLI_BUILD=0

            docker compose build
            docker compose up -d --wait --wait-timeout 180

            echo "Clearing docker cache/unused things"
            docker system prune -a --volumes -f

            echo "✨ Deployment successful"
