name: CD

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 using SSH Action
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            set -euo pipefail
            cd Feedback-Sentiment

            git fetch origin develop
            git reset --hard origin/develop
            echo "Deploying latest commit on develop: $(git rev-parse HEAD)"

            docker-compose build
            docker-compose up -d --remove-orphans

            echo "Waiting for services..."
            sleep 10

            docker system prune -f
            echo "✨ Deployment successful"
